### ISSUE TITLE
Start a newsletter 

### ISSUE THREAD

**Issue by kyyberi** [kyyberi/100daysofDX#32]
Feedback and idea came from a follower: 

"Very cool - yes, I started following the 100 days articles even though I would love to get them via a newsletter (I'm sure I can't get myself to time and look at it every day) :) I would love to contribute to the content, actually."

This might help some of the readers to follow and reduce the FOMO - fear of missing out.

This could be done for example with https://curated.co/

**Comment by agraebe** [comment]
Fixed with https://github.com/kyyberi/100daysofDX/pull/41

**Comment by kyyberi** [comment]
Reviewed and merged, closing.
