### ISSUE TITLE
DX vs UX - Battle or Middle Ground? (37) 19.8.2019

### ISSUE THREAD

**Issue by Nazarah** [kyyberi/100daysofDX#86]
## Description

- This post would be a diary like experience gained by an UX designer when working side by side with Developers in a new platform technology 
- UX designers are often accused of staying too far away from the technological constraints while designing service experiences for intended users. The accusation are occasionally made by core developers indicating UX designers don't care about internal developer experience, especially when working on a project aiming at Developers. The job of gaining their confidence hard, but not impossible. How I worked my way in within my current workplace, I will provide the directions I followed.
- The balance between co-existence, compromise and holding your own ground.

**Comment by kyyberi** [comment]
Sounds great! Just put this in branch. You have a guestimate of the date this would be ready?

**Comment by Nazarah** [comment]
I am aiming towards next Monday. Sounds fair?

**Comment by kyyberi** [comment]
So Monday 19th would be post number 37 -> "feature/day37"
